# ASTR 598 Notes:

## Feb 5:

In [7]:
class PriorityQueue(object):

    def __init__(self, MAX=0):
        self.a = [0]
        self.N = 0
        self.max = MAX
        return None

    def min(self):
        """Error code"""
        self.m = self.a[1]
        return self.m

    def size(self):
        return self.N

    def isEmpty(self):
        if len(self.a) == 0:
            return True
        else:
            return False

    def isFull(self):
        if True:
            pass
        return False

    def insert(self, i):
        self.i = i
        self.temp = 0
        self.k = N
        self.N += 1
        if self.N > self.max:
            a[self.N] = self.i
            return Error
            k = self.N
        while (self.k > 1) and (self.a[self.k/2] > self.a[self.k]):
            """
            heapsort O(NlogN)

            as long as not at root and as long as parents value is 
            > child do something 

            for child of index k:
            parent index is k/2 

            !!!!! integer division super important
            """

            # exchange parent and child
            temp = a[self.k/2]
            a[self.k/2] = a[self.k]
            a[self.k] = temp
            k = k/2
        return None
    
    def delMin(self):
        if N == 0:
            print "Error"
            return None
        else:
            self.min = self.a[1]
            self.a[1] = self.a[N]
            self.a[N] = 0

            # loop backwards
            N = N - 1
            k = 1
            while 2*k <= N:
                # left child
                if (2*k == N) or (self.a[2*k] < self.a[2*k+1]):
                    j = 2*k # lesser child or only child
                else:
                    j = 2*k + 1 # right child and is the smaller child
                    
                # only child or lesser child
                if (self.a[k] > a[j]):
                    temp = a[k]
                    a[k] = a[j]
                    k = j
                else:
                    break
            return self.min

## Algorithm: mergesort

Takes two sorted lists and merges them into a sorted list

In [15]:
def merge(a, b, c):
    
    """ Takes two sorted lists and merges them into a sorted list specified
        upon calling. 
        
        O(NlogN)
    """
    k = 0 # c
    i = 0 # a
    j = 0 # b
    
    
    while (i <  len(a)) and (j < len(b)):
        if a[i] < b[j]:
            c[k] = a[i]
            i += 1
            k += 1
        else:
            c[k] = b[j]
            j += 1
            k += 1
    #  only one of these two will run 
    # fills in the rest of c if a or b are finished
    while i < len(a):
        c[k] = a[i]
        i += 1
        k += 1 
    
    while j < len(b):
        c[k] = b[j]
        j += 1
        k +=1
    return None

In [10]:
import numpy as np

In [27]:
a = np.sort(np.random.randint(100,size=5))
b = np.sort(np.random.randint(100,size=8))

c = np.zeros(len(a)+len(b))

merge(a,b,c)

In [28]:
print a, b, c

[11 37 41 47 48] [ 0  4 20 26 69 83 89 93] [  0.   4.  11.  20.  26.  37.  41.  47.  48.  69.  83.  89.  93.]


## Feb 12:

Going over HWs:

#### HW1:

1) units in readme and comments

2) $F = Gm1m2/(r^2)$ where $r = sqrt((x1-x2)^2 + (y1-y2)^2)$
    dont use x1==x2 if floats. use abs(x1-x2) < epsilon
    
3) use composition instead of inheritance

4) efficiency: dont compute sqrt if you are going to square


#### HW2:
(LinkedList)

1) check for Null

2) @staticmethod generally dont use them 
    static gives you math.complex.add(c1,c2)
    non static would be c1.add(c2)

3) dont use file names that are key names

#### HW3:

1) check for empyt stack during pop(), or top()

2) make errors real and exit

    if (x == None):
        print error # error should have a real string 
        break # exit the loop 

        then you dont need an else unless you have more than two cases
    
3) read the question

#### python specific stuff

    class Complex:
        # constructor
        def __init__(self, r=0.0, i=0.0):
            self.real = r
            self.imag = i
            
        def hello:
            self.xyz # dont do this. Self only goes on the variables from the constructor
            
            


### StableSorts

after sorting still have the correct order 

mergesort is a stable sort

Heapsort is NOT a stable sort

    unosrted                                  sorted
    keys
    -                                          - 
    -                                          - 
    -                                          - 
    chicago 11:00am                            chicago 1100
    -                                          chicago 1300
    -                                          - 
    chicago 13:00hrs                           - 
    -                                          - 


#### finishing up mergesort:

    a[] = [3][5][17][][][][][][][][][]

    result c[] = [1 from b][2 from b][3 from a][][][][][][][][][][][][]

    b[] = [1][2][4][5][]

In [18]:
class mergesort(object):
    def __init__(self, a):
        #self.aux = []*len(a)
        # overloading funciton ok since takes a different amount of input
        # signature of function is different so computer names them differently
        sort(a, 0, len(a)-1)
        return None

    #need aux as a global veriable
    #aux = []*len(a)
    #sort(a, 0, len(a)-1)


    def sort(a, low, hi):
        # base case of recursion to end recursion
        if (hi <= low):
            return None

        #      low        mid        hi
        # []   []   []   []    []    []    []
        mid = low + (hi - low)/2

        # calling a function in a definition of that function
        # this is what recursion is

        # DIVIDE and CONQUER!!!!!
        # sort left half

        # if the parameters were equal to the initial parameters it would run forever
        sort(a, low, mid) 

        # sort right half
        sort(a, mid+1, hi) 

        #now merge the two sorted halfs
        merge(a, low, mid, hi)


    def merge(a, lo, mid, hi):
        i = lo
        j = mid + 1

        # make a copy
        aux = [0]*len(a)
        for k in range(lo, hi + 1):
            aux[k] = a[k]

        # could just copy
        #aux = np.copy(a)

        k = lo
        while (k <= hi):
            while((i <= mid) and (j <= hi)):

                if(aux[j] < aux[i]):
                    #pick the smaller one
                    aux[k] = aux[j]
                    k = k + 1
                    j = j + 1
                else:
                    a[k] = aux[i]
                    i = i + 1 
                    k = k + 1 

            # Now either i > mid or j > hi
            # so only one of the below loops will run
            while(i <= mid):
                a[k] = aux[i]
                i = i + 1
                k = k + 1 
            while(j <= hi):
                a[k] = aux[j]
                j = j + 1
                k = k + 1
        return None    

Divide and Conquer:

height is logN: 

         [][][][][][][][][]
            /       \
        [][][][]    [][][][][]
          /  \       /      \
       [][]  [][]   [][][]   [][]
    


Quicksort is Not stable

In [23]:
import numpy as np
a = np.random.randint(0, 100, 10)

In [24]:
b = list(a)

In [25]:
b

[36, 60, 16, 38, 29, 12, 82, 2, 6, 15]

In [26]:
c = a.copy()

In [27]:
print a, c

[36 60 16 38 29 12 82  2  6 15] [36 60 16 38 29 12 82  2  6 15]


In [28]:
d = np.copy(b)

In [29]:
print d

[36 60 16 38 29 12 82  2  6 15]


In [30]:
merge(b, 1, len(b)/2, len(b)-1)

In [31]:
b

[36, 60, 16, 38, 29, 12, 82, 2, 6, 15]